apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      io.dev.service: web1
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: 0.0.0.0/0
    name: web1
    namespace: palm
  spec:
    ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    selector:
      io.dev.service: web1
    type: LoadBalancer

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      io.dev.service: web2
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: 0.0.0.0/0
    name: web2
    namespace: palm
  spec:
    ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
    selector:
      io.dev.service: web2
    type: LoadBalancer

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      io.dev.service: web3
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: 0.0.0.0/0
    name: web3
    namespace: palm
  spec:
    ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
    selector:
      io.dev.service: web3
    type: LoadBalancer


- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      io.dev.service: web1
    name: web1
    namespace: palm
  spec:
    replicas: 2
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.dev.service: web1
      spec:
        containers:
        - image:  370913028188.dkr.ecr.us-east-1.amazonaws.com/palm:1.0
          name: web1
          imagePullPolicy: "Always"
          ports:
          - containerPort: 8080

        imagePullSecrets:
        - name: docker-dailyupdatecredentials
        restartPolicy: Always
  status: {}

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      io.dev.service: web2
    name: web2
    namespace: palm
  spec:
    replicas: 2
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.dev.service: web2
      spec:
        containers:
        - image: 370913028188.dkr.ecr.us-east-1.amazonaws.com/palm:2.0
          name: web2
          imagePullPolicy: "Always"
          ports:
          - containerPort: 8081

        imagePullSecrets:
        - name: docker-dailyupdatecredentials
        restartPolicy: Always
  status: {}

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      io.dev.service: web3
    name: web3
    namespace: palm
  spec:
    replicas: 2
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.dev.service: web3
      spec:
        containers:
        - image: 370913028188.dkr.ecr.us-east-1.amazonaws.com/palm:3.0
          name: web3
          imagePullPolicy: "Always"
          ports:
          - containerPort: 8082

        imagePullSecrets:
        - name: docker-dailyupdatecredentials
        restartPolicy: Always
  status: {}